# Generated by Django 4.1.3 on 2023-05-22 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_detalleorden_precio_unitario_alter_orden_fecha_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
